--
-- Schema Sync 0.1.1 Patch Script
-- Created: Tue, Mar 08, 2016
-- Server Version: 5.5.47-0ubuntu0.14.04.1
-- Apply To: localhost/other
--

USE `other`;
CREATE TABLE `Products_producttaxmastermapping` ( `id` int(11) NOT NULL AUTO_INCREMENT, `base_product_id` int(11) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `attribute` ( `attribute_id` int(10) unsigned NOT NULL, `attribute_type` varchar(45) DEFAULT NULL, `attribute_code` varchar(45) DEFAULT NULL, `attribute_name` varchar(100) DEFAULT NULL, `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP, `modified_date` timestamp NULL DEFAULT NULL, `is_deleted` smallint(6) NOT NULL DEFAULT '0', `is_searchable` smallint(6) NOT NULL DEFAULT '0') ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `attributes_data` ( `id` int(11) NOT NULL AUTO_INCREMENT, `base_product_id` int(11) NOT NULL, `subscribed_product_id` int(11) NOT NULL, `category_id` int(11) NOT NULL, `variant` varchar(255) DEFAULT NULL, `variant_value` varchar(255) DEFAULT NULL, `key_features` text, `specifications` text, `uom1` varchar(255) DEFAULT NULL, `uom2` varchar(255) DEFAULT NULL, `combo` text, `model_number` varchar(255) DEFAULT NULL, `slug` text, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `auth_group` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(80) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `auth_group_permissions` ( `id` int(11) NOT NULL AUTO_INCREMENT, `group_id` int(11) NOT NULL, `permission_id` int(11) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `group_id` (`group_id`,`permission_id`), KEY `auth_group__permission_id_1f49ccbbdc69d2fc_fk_auth_permission_id` (`permission_id`), CONSTRAINT `auth_group_permission_group_id_689710a9a73b7457_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`), CONSTRAINT `auth_group__permission_id_1f49ccbbdc69d2fc_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `auth_permission` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `content_type_id` int(11) NOT NULL, `codename` varchar(100) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `content_type_id` (`content_type_id`,`codename`), CONSTRAINT `auth__content_type_id_508cf46651277a81_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `auth_user` ( `id` int(11) NOT NULL AUTO_INCREMENT, `password` varchar(128) NOT NULL, `last_login` datetime DEFAULT NULL, `is_superuser` tinyint(1) NOT NULL, `username` varchar(30) NOT NULL, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(254) NOT NULL, `is_staff` tinyint(1) NOT NULL, `is_active` tinyint(1) NOT NULL, `date_joined` datetime NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `username` (`username`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `auth_user_groups` ( `id` int(11) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL, `group_id` int(11) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `user_id` (`user_id`,`group_id`), KEY `auth_user_groups_group_id_33ac548dcf5f8e37_fk_auth_group_id` (`group_id`), CONSTRAINT `auth_user_groups_group_id_33ac548dcf5f8e37_fk_auth_group_id` FOREIGN KEY (`group_id`) REFERENCES `auth_group` (`id`), CONSTRAINT `auth_user_groups_user_id_4b5ed4ffdb8fd9b0_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `auth_user_user_permissions` ( `id` int(11) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL, `permission_id` int(11) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `user_id` (`user_id`,`permission_id`), KEY `auth_user_u_permission_id_384b62483d7071f0_fk_auth_permission_id` (`permission_id`), CONSTRAINT `auth_user_user_permissi_user_id_7f0938558328534a_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`), CONSTRAINT `auth_user_u_permission_id_384b62483d7071f0_fk_auth_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `auth_permission` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `django_admin_log` ( `id` int(11) NOT NULL AUTO_INCREMENT, `action_time` datetime NOT NULL, `object_id` longtext, `object_repr` varchar(200) NOT NULL, `action_flag` smallint(5) unsigned NOT NULL, `change_message` longtext NOT NULL, `content_type_id` int(11) DEFAULT NULL, `user_id` int(11) NOT NULL, PRIMARY KEY (`id`), KEY `djang_content_type_id_697914295151027a_fk_django_content_type_id` (`content_type_id`), KEY `django_admin_log_user_id_52fdd58701c5f563_fk_auth_user_id` (`user_id`), CONSTRAINT `django_admin_log_user_id_52fdd58701c5f563_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`), CONSTRAINT `djang_content_type_id_697914295151027a_fk_django_content_type_id` FOREIGN KEY (`content_type_id`) REFERENCES `django_content_type` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `django_content_type` ( `id` int(11) NOT NULL AUTO_INCREMENT, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `django_content_type_app_label_45f3b1d93ec8c61c_uniq` (`app_label`,`model`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `django_session` ( `session_key` varchar(40) NOT NULL, `session_data` longtext NOT NULL, `expire_date` datetime NOT NULL, PRIMARY KEY (`session_key`), KEY `django_session_de54fa62` (`expire_date`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `old_store__price_mapping` ( `id` int(11) NOT NULL AUTO_INCREMENT, `base_product_id` int(11) NOT NULL, `subscribed_product_id` int(11) DEFAULT NULL, `store_id` int(11) NOT NULL, `store_price` decimal(12,4) NOT NULL, `store_offer_price` decimal(12,4) NOT NULL, `lead_time` int(10) NOT NULL DEFAULT '0', `publish` int(11) NOT NULL DEFAULT '1', `unit_price` decimal(12,4) NOT NULL, `secondary_store_price` decimal(12,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (`id`), UNIQUE KEY `unique_index` (`base_product_id`,`subscribed_product_id`,`store_id`), KEY `base_product_id` (`base_product_id`,`store_offer_price`), KEY `subscribed_product_id` (`subscribed_product_id`,`store_offer_price`), KEY `base_product_id_2` (`base_product_id`,`store_offer_price`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `popular_products` ( `id` int(11) NOT NULL AUTO_INCREMENT, `mc_id` int(11) NOT NULL, `sc_id` int(11) NOT NULL, `base_product_id` int(11) NOT NULL, `product_title` varchar(255) DEFAULT NULL, `product_image` varchar(255) DEFAULT NULL, `product_slug` text, `store_price` decimal(12,4) DEFAULT NULL, `min_store_price` decimal(12,4) DEFAULT NULL, `store_id` int(11) DEFAULT NULL, `publish` tinyint(2) NOT NULL DEFAULT '1', `unit_of_measurement_one` varchar(150) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `supplified_masterimportupload` ( `id` int(11) NOT NULL AUTO_INCREMENT, `file_name` varchar(500) NOT NULL, `process_name` varchar(300) NOT NULL, `process_type` varchar(50) NOT NULL, `uploaded_on` datetime DEFAULT NULL, `applied_on` datetime DEFAULT NULL, `query` longtext, `error` longtext, `applied` tinyint(1) NOT NULL, `discarded_on` datetime DEFAULT NULL, `ref_text` varchar(500) DEFAULT NULL, `applied_on_production` tinyint(1) NOT NULL, `file_path` varchar(100) DEFAULT NULL, `user_id` int(11) NOT NULL, `download_query` longtext, `applied_on_production_time` datetime DEFAULT NULL, `sql_error` longtext, `sync_errors` longtext, `sync_query` longtext, `master_category_id` int(11) DEFAULT NULL, PRIMARY KEY (`id`), KEY `supplified_masterimportupload_e8701ad4` (`user_id`), CONSTRAINT `supplified_masterimport_user_id_5d18d1764e0c37f4_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE `prod_base_product`;
DROP TABLE `prod_store_price_mapping`;
DROP TABLE `prod_subscribed_product`;
ALTER TABLE `Products_attributes` ADD COLUMN `ascii_ignd_name` mediumtext NULL AFTER `display_name`, MODIFY COLUMN `name` varchar(255) NULL AFTER `id`, MODIFY COLUMN `display_name` varchar(255) NULL AFTER `name`, ADD UNIQUE INDEX `name` (`name`) USING BTREE, ADD INDEX `name_2` (`name`) USING BTREE, CHARSET=utf8 COLLATE=utf8_general_ci;
ALTER TABLE `Products_categoryattributesmapping` ADD COLUMN `change_log_id` text NULL AFTER `status`, ADD COLUMN `filter_sequence` int(11) NOT NULL DEFAULT '0' AFTER `change_log_id`;
ALTER TABLE `Products_productcategoryattributesmappingfilters` MODIFY COLUMN `text_value` varchar(100) NULL AFTER `subscribed_ref_id`, ADD INDEX `decimal_value` (`decimal_value`) USING BTREE, ADD INDEX `int_value` (`int_value`) USING BTREE, ADD INDEX `text_value` (`text_value`) USING BTREE;
ALTER TABLE `base_product` ADD COLUMN `video_link` varchar(500) NULL AFTER `sub_sub_category`;
ALTER TABLE `category` ADD COLUMN `category_icon` varchar(255) NULL AFTER `display_in_menu`, ADD COLUMN `category_description` text NULL AFTER `category_icon`;
ALTER TABLE `history_mycart` DROP COLUMN `region_id`, DROP COLUMN `store_code`, DROP COLUMN `unit_of_measurement_one`, DROP COLUMN `install_qty`, DROP COLUMN `install_amount`, DROP COLUMN `installation_moq`, DROP COLUMN `installation_uom`, DROP COLUMN `moq_increment`, DROP COLUMN `category_id`, DROP COLUMN `brand_id`, DROP COLUMN `variant_details`, DROP COLUMN `moq_sme`, DROP COLUMN `moq_enterprise`, DROP COLUMN `moq_increment_enterprise`, DROP COLUMN `moq_enterprise_price`, DROP COLUMN `moq_sme_price`, DROP COLUMN `moq_increment_sme`, MODIFY COLUMN `user_id` int(11) NULL AFTER `id`, ADD INDEX `user_id` (`user_id`) USING BTREE;
ALTER TABLE `login` DROP COLUMN `enterprise_login`, DROP COLUMN `group_type`;
ALTER TABLE `mycart` DROP COLUMN `region_id`, DROP COLUMN `store_code`, DROP COLUMN `deleted_date`, DROP COLUMN `unit_of_measurement_one`, DROP COLUMN `install_qty`, DROP COLUMN `install_amount`, DROP COLUMN `installation_moq`, DROP COLUMN `installation_uom`, DROP COLUMN `moq_increment`, DROP COLUMN `category_id`, DROP COLUMN `brand_id`, DROP COLUMN `variant_details`, DROP COLUMN `moq_sme`, DROP COLUMN `moq_enterprise`, DROP COLUMN `moq_increment_enterprise`, DROP COLUMN `moq_enterprise_price`, DROP COLUMN `moq_sme_price`, DROP COLUMN `moq_increment_sme`, DROP COLUMN `mapped_category_id`, MODIFY COLUMN `product_qty` int(11) NOT NULL AFTER `variant_id`;
ALTER TABLE `order_header` DROP COLUMN `affiliate_utm_source`, DROP COLUMN `affiliate_gclid`, DROP COLUMN `affiliate_campaign_id`;
ALTER TABLE `order_line` DROP COLUMN `store_code`, DROP COLUMN `unit_of_measurement_one`, DROP COLUMN `install_unit_price`, DROP COLUMN `install_qty`, DROP COLUMN `install_amount`, DROP COLUMN `installation_moq`, DROP COLUMN `installation_uom`, DROP COLUMN `variant_details`, MODIFY COLUMN `product_qty` int(11) NULL AFTER `product_name`, MODIFY COLUMN `status` enum('processing','payment-pending','exportable','exported','po-created','ready-to-pickup','fullfillment-center','invoice-created','qc-packaging','shipped','delivered','closed','return-request','policy-not-applicable','return-denied','return-accepted','returned','to-be-returned-to-vendor','new-proc-exchange','exchange','refund','closed','order-cancelled') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `shipping_charges`;
ALTER TABLE `product_pincode_mapping` DROP INDEX `unique_store_product_pincode`;
ALTER TABLE `promocode` DROP COLUMN `category_ids`, DROP COLUMN `brand_ids`, DROP COLUMN `group_type`, DROP COLUMN `max_discount`, DROP COLUMN `applying_count_limit`;
ALTER TABLE `store_price_mapping` ADD COLUMN `moq_enterprise_price` decimal(12,4) NOT NULL DEFAULT '0.0000' AFTER `secondary_store_price`, ADD COLUMN `moq_sme` decimal(12,4) NOT NULL DEFAULT '0.0000' AFTER `moq_enterprise_price`, ADD COLUMN `moq_sme_price` varchar(100) NOT NULL AFTER `moq_sme`, ADD COLUMN `moq_increment_sme` decimal(12,4) NOT NULL DEFAULT '0.0000' AFTER `moq_sme_price`, MODIFY COLUMN `moq_retail` decimal(12,4) NOT NULL DEFAULT '1.0000' AFTER `markup`, MODIFY COLUMN `moq_incremental_retail` decimal(12,4) NOT NULL DEFAULT '1.0000' AFTER `moq_retail`, MODIFY COLUMN `moq_enterprise` decimal(12,4) NOT NULL DEFAULT '1.0000' AFTER `moq_incremental_retail`, MODIFY COLUMN `moq_increment_enterprise` decimal(12,4) NOT NULL DEFAULT '1.0000' AFTER `moq_enterprise`, MODIFY COLUMN `processing_time` text NULL AFTER `is_returnable`;
